### PR TITLE
Avoid messing with the version of Pitest used by the Maven plugin

### PR DESCRIPTION
**Pull request by tmortagne**

### CODE REVIEW

**Comment by oscarlvp** [comment]
Could you please explain a little bit why do we need this change?

**Comment by tmortagne** [comment]
This JAR is by definition used in a context where pitest is already in the classpath so they are not needed but more importantly when you use Descartes with the pitest plugin other than 1.4.7 (for example using the lastest version of Pitest with Descartes) you make it use 1.4.7 instead of the version the plugin was built with because of the way Maven dependencies works.

**Comment by oscarlvp** [comment]
OK. And I assume this also helps to adopt newer versions of PIT without waiting for a new Descartes release.

**Comment by tmortagne** [comment]
That's the idea yes. There is no issue when you use the version of pitest Descartes was built with.

**Pull request merged**
